### ISSUE TITLE
Always delete noteImages suggestion

### ISSUE THREAD

**Issue by matiasleidemer** [epicweb-dev/data-modeling#33]
Here there, Kent 👋 

I'm doing the EpicWeb course, which has been really good so far; thank you! I would like to leave a suggestion to the [07. UPDATING DATA / 02. UPDATE](http://localhost:5639/07/02/solution) solution page: 

What if, instead of checking if we have new images or image updates, we always delete and recreate them (if any)? We wouldn't need to `transform` the `NoteEditorSchema` and would make the code easier to follow. The downside is that we would always bust the image cache (which isn't a big deal in this case specifically).

Maybe it would be nice to leave a note on the solution page mentioning that the approach above is possible. WDYT?

Thank you!

**Comment by kentcdodds** [comment]
Thanks for the suggestion. Once we get to the last part of this exercise the resulting code is quite nice and optimized for our use case: https://data.epicweb.dev/07/04/solution

What do you think of the final solution?

**Comment by matiasleidemer** [comment]
The final solution looks great, and once all the `imageUpdates` and `newImages` are set, updating them using Prisma is a breeze. IMO, getting the updates and new images adds a lot of complexity, and it could be avoided if we just delete and recreate everything all the time. It's all good, however. 😄

**Comment by kentcdodds** [comment]
The problem is it's just a lot of extra work on the server and database for only subjective minimal benefit.

Thanks for the feedback though!
